name: Docker Production Pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8.2

    - name: pip install pyarmor
      run: pip install pyarmor==6.2.2

    - name: pyarmor
      run: pyarmor obfuscate main.py --exclude test.py

    - name: docker build
      run: docker build -f Dockerfile.prod -t python-demo .